name: Build Client

on:
  push:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install app dependencies
        working-directory: ./client
        run: npm install

      - name: Build app
        working-directory: ./client
        run: npm run build

      - name: Capacitor sync
        working-directory: ./client
        run: npx cap sync

      - name: Build Android AssembleDebug
        working-directory: ./client
        run: cd android && ./gradlew AssembleDebug

      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: client/android/app/build/outputs/apk/debug/app-debug.apk
