name: Build Client

on:
  push:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout source
        uses: actions/checkout@3

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install app dependencies
        working-directory: ./client
        run: npm install

      - name: Build app
        working-directory: ./client
        run: npm run build

      - name: Capacitor sync
        working-directory: ./client
        run: npx cap sync

      - name: Build Android AssembleDebug
        working-directory: ./client
        run: cd android && gradle AssembleDebug

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: client/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 60
