name: Build Client

on:
  pull_request:
    paths:
      - 'client/**'  
  push:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      ${{
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' &&
      github.event.pull_request.head.repo.full_name != 'mirsella/powercontrol')
      }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install app dependencies
        working-directory: ./client
        run: npm install

      - name: Build app
        working-directory: ./client
        run: npm run build

      - name: Capacitor update
        working-directory: ./client
        run: npx cap update

      - name: Capacitor copy
        working-directory: ./client
        run: npx cap copy

      - name: Build Android AssembleDebug
        working-directory: ./client
        run: cd android && gradle AssembleDebug

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: client/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 60
