name: build Server

on:
  pull_request:
    paths:
      - 'server/**'
  push:
    paths:
      - 'server/**'    

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      ${{
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' &&
      github.event.pull_request.head.repo.full_name != 'mirsella/powercontrol')
      }}    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
         languages: typescript, javascript
         config-file: ./.github/codeql/codeql-config-server.yml


      - name: Install app dependencies
        working-directory: ./server
        run: npm install

      - name: build TS
        working-directory: ./server
        run: npm run build
