name: build Server

on:
  push:
    branches:
      - main
    paths:
      - '/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install app dependencies
        working-directory: ./server
        run: npm install

      - name: build TS
        working-directory: ./server
        run: npm run build
